version: '3.8'

services:
  dynamodb-local:
    image: "instructure/dynamo-local-admin"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "./.db_data:/data"
    expose:
      - "8000"
